import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { AOSInit } from "@/components/AosInit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Heart of Fantasy, an MMORPG permadeath",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <AOSInit />
      <body
        className={`${geistSans.className} antialiased`}
      >
        {children}
      <footer className="container">
        asdasd
        <hr />
        Created by Alejandro Poveda Bisquert
      </footer>
      </body>
    </html>
  );
}
